version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: daily
      time: "13:00"
    open-pull-requests-limit: 10
    reviewers:
      - patrick.zippenfenig
    allow:
      - dependency-type: direct
    commit-message:
      prefix: "fix: "
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
      time: "13:00"
    commit-message:
      prefix: "fix: "
